// apps/web/src/components/marketplace/mock-issues.ts
// Realistic mock bounty issues for development, testing, and fallback
// Trâm (UI/UX Designer & Test Engineer)

import type { IssueItem } from "./issue-card";

export const MOCK_ISSUES: IssueItem[] = [
  {
    id: "iss-1",
    title: "[Bảo Mật] Kiểm toán & Vá lỗi Reentrancy trong Escrow mutualCancel",
    description:
      "Phát hiện nguy cơ reentrancy trong hàm mutualCancel khi người dùng yêu cầu rút tiền cọc. Cần bổ sung modifier nonReentrant, tuân thủ Checks-Effects-Interactions pattern và viết 5 unit test kiểm chứng bằng Hardhat.",
    category: "AUDIT",
    status: "OPEN",
    bountyAmount: 750,
    token: { symbol: "USDT", name: "Tether USD" },
    requiredSkills: ["solidity", "security-audit", "hardhat", "reentrancy"],
    difficulty: "EXPERT",
    timeEstimate: "2 ngày",
    viewCount: 342,
    applicationCount: 4,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    client: {
      id: "cl-1",
      name: "Satoshi_Labs",
      walletAddress: "0x8a90CAB1c62ada3699546a3daEEf0C55F7A2600E",
      reputationScore: 185,
      isGithubVerified: true,
    },
  },
  {
    id: "iss-2",
    title: "Tối ưu hóa GraphQL Yoga Resolver với DataLoader chống N+1 Query",
    description:
      "Query danh sách Issue và Application đang bị nghẽn do N+1 database queries khi load thông tin Client và Token. Cần triển khai Pothos dataloader plugin hoặc custom batch loader cho Prisma client.",
    category: "BUG_FIX",
    status: "OPEN",
    bountyAmount: 400,
    token: { symbol: "USDT", name: "Tether USD" },
    requiredSkills: ["graphql", "typescript", "prisma", "nodejs"],
    difficulty: "INTERMEDIATE",
    timeEstimate: "3 ngày",
    viewCount: 189,
    applicationCount: 2,
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    client: {
      id: "cl-2",
      name: "Alex Nguyen",
      walletAddress: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
      reputationScore: 92,
      isGithubVerified: true,
    },
  },
  {
    id: "iss-3",
    title: "Xây dựng Chat Realtime Sidebar bằng Socket.io + Monaco Code Preview",
    description:
      "Dựng khung chat tương tác trực tiếp giữa Client và Developer trong màn hình chi tiết bài toán. Tích hợp Monaco Editor preview snippet code, hỗ trợ đính kèm file và che thông tin nhạy cảm (AI Guard).",
    category: "FEATURE",
    status: "OPEN",
    bountyAmount: 600,
    token: { symbol: "USDT", name: "Tether USD" },
    requiredSkills: ["nextjs", "react", "socketio", "tailwind", "monaco"],
    difficulty: "INTERMEDIATE",
    timeEstimate: "4 ngày",
    viewCount: 275,
    applicationCount: 5,
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    client: {
      id: "cl-3",
      name: "CyberPunk_DAO",
      walletAddress: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
      reputationScore: 210,
      isGithubVerified: false,
    },
  },
  {
    id: "iss-4",
    title: "Triển khai EIP-712 Typed Data Off-chain Signature Verification",
    description:
      "Viết hàm verifyCommitment trên Smart Contract BloodyRoarEscrow để xác thực chữ ký off-chain của Client trước khi gửi giao dịch nạp tiền ký quỹ (lazy deposit pattern).",
    category: "SMART_CONTRACT",
    status: "OPEN",
    bountyAmount: 850,
    token: { symbol: "USDT", name: "Tether USD" },
    requiredSkills: ["solidity", "eip712", "cryptography", "base-sepolia"],
    difficulty: "EXPERT",
    timeEstimate: "2 ngày",
    viewCount: 420,
    applicationCount: 6,
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    client: {
      id: "cl-1",
      name: "Satoshi_Labs",
      walletAddress: "0x8a90CAB1c62ada3699546a3daEEf0C55F7A2600E",
      reputationScore: 185,
      isGithubVerified: true,
    },
  },
  {
    id: "iss-5",
    title: "Tích hợp Gemini 1.5 Flash sinh tự động Bộ Test Cases Given-When-Then",
    description:
      "Tạo AI Prompt pipeline nhận mô tả yêu cầu bài toán từ Client, tự động phân tích và sinh ra 5-8 test cases theo cú pháp BDD Given/When/Then, lưu vào DB và hiển thị trên giao diện review.",
    category: "DATA_SCIENCE",
    status: "OPEN",
    bountyAmount: 500,
    token: { symbol: "USDT", name: "Tether USD" },
    requiredSkills: ["ai-llm", "gemini-api", "prompt-engineering", "typescript"],
    difficulty: "INTERMEDIATE",
    timeEstimate: "3 ngày",
    viewCount: 310,
    applicationCount: 3,
    createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    client: {
      id: "cl-4",
      name: "DevGuild_VN",
      walletAddress: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
      reputationScore: 145,
      isGithubVerified: true,
    },
  },
  {
    id: "iss-6",
    title: "Xây dựng Dashboard Quản lý Bounty dành cho Client (My Tasks Overview)",
    description:
      "Thiết kế và triển khai trang /dashboard/client hiển thị danh sách task đã đăng, trạng thái ký quỹ Escrow, số đơn ứng tuyển, và hành động nhanh (chọn Developer, release bounty). Dùng TanStack Table để render bảng dữ liệu phân trang.",
    category: "FEATURE",
    status: "IN_PROGRESS",
    bountyAmount: 0.35,
    token: { symbol: "ETH", name: "Ethereum" },
    requiredSkills: ["nextjs", "react", "tanstack-table", "tailwind", "graphql"],
    difficulty: "INTERMEDIATE",
    timeEstimate: "4 ngày",
    viewCount: 198,
    applicationCount: 7,
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    client: {
      id: "cl-3",
      name: "CyberPunk_DAO",
      walletAddress: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
      reputationScore: 210,
      isGithubVerified: false,
    },
  },
  {
    id: "iss-7",
    title: "Thiết lập CI/CD Pipeline với GitHub Actions: Lint, Test & Deploy Preview",
    description:
      "Cấu hình workflow GitHub Actions tự động chạy bun run lint, bun run typecheck và bun run test trên mọi PR. Tích hợp Vercel Preview Deployment cho nhánh feature và Slack notification khi build thất bại.",
    category: "DEVOPS",
    status: "COMPLETED",
    bountyAmount: 250,
    token: { symbol: "USDC", name: "USD Coin" },
    requiredSkills: ["github-actions", "devops", "vercel", "bash", "docker"],
    difficulty: "BEGINNER",
    timeEstimate: "1 ngày",
    viewCount: 512,
    applicationCount: 11,
    createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    client: {
      id: "cl-2",
      name: "Alex Nguyen",
      walletAddress: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
      reputationScore: 92,
      isGithubVerified: true,
    },
  },
  {
    id: "iss-8",
    title: "Phân tích & Phát hiện Wallet Drainer Pattern bằng Machine Learning",
    description:
      "Xây dựng mô hình phân loại giao dịch on-chain nghi ngờ sử dụng scikit-learn + Python, tích hợp API endpoint FastAPI để frontend gọi kiểm tra địa chỉ ví trước khi ký giao dịch. Độ chính xác tối thiểu 90% trên test set Ethereum Mainnet.",
    category: "DATA_SCIENCE",
    status: "OPEN",
    bountyAmount: 1200,
    token: { symbol: "USDC", name: "USD Coin" },
    requiredSkills: ["python", "scikit-learn", "fastapi", "web3py", "ml"],
    difficulty: "EXPERT",
    timeEstimate: "7 ngày",
    viewCount: 631,
    applicationCount: 2,
    createdAt: new Date(Date.now() - 90 * 3600 * 1000).toISOString(),
    client: {
      id: "cl-1",
      name: "Satoshi_Labs",
      walletAddress: "0x8a90CAB1c62ada3699546a3daEEf0C55F7A2600E",
      reputationScore: 185,
      isGithubVerified: true,
    },
  },
  {
    id: "iss-9",
    title: "Triển khai Hệ thống Reputation Score On-chain với Soulbound Token (SBT)",
    description:
      "Viết Solidity contract SBT (ERC-5192 non-transferable) lưu điểm danh tiếng của Developer sau mỗi bounty hoàn thành. Tích hợp event emitter để backend lắng nghe và cập nhật DB. Bao gồm script mint, burn và upgrade qua proxy pattern.",
    category: "SMART_CONTRACT",
    status: "IN_PROGRESS",
    bountyAmount: 0.6,
    token: { symbol: "ETH", name: "Ethereum" },
    requiredSkills: ["solidity", "erc-5192", "openzeppelin", "hardhat", "proxy-pattern"],
    difficulty: "EXPERT",
    timeEstimate: "5 ngày",
    viewCount: 487,
    applicationCount: 5,
    createdAt: new Date(Date.now() - 110 * 3600 * 1000).toISOString(),
    client: {
      id: "cl-4",
      name: "DevGuild_VN",
      walletAddress: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
      reputationScore: 145,
      isGithubVerified: true,
    },
  },
  {
    id: "iss-10",
    title: "Tối ưu Performance Trang Marketplace: Code Splitting, Image Lazy Load & LCP < 2s",
    description:
      "Phân tích Lighthouse report hiện tại (LCP ~4.2s, TTI ~5.8s) và áp dụng các kỹ thuật tối ưu: dynamic import cho heavy components, next/image với blur placeholder, font subsetting, và preloading critical CSS. Mục tiêu đạt Lighthouse Performance score ≥ 90.",
    category: "UI_UX",
    status: "OPEN",
    bountyAmount: 300,
    token: { symbol: "USDC", name: "USD Coin" },
    requiredSkills: ["nextjs", "performance", "lighthouse", "webpack", "core-web-vitals"],
    difficulty: "INTERMEDIATE",
    timeEstimate: "2 ngày",
    viewCount: 223,
    applicationCount: 4,
    createdAt: new Date(Date.now() - 130 * 3600 * 1000).toISOString(),
    client: {
      id: "cl-5",
      name: "BuildFast_VC",
      walletAddress: "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65",
      reputationScore: 78,
      isGithubVerified: false,
    },
  },
];
